"""relationship loc activity

Revision ID: 0ac8a2341b50
Revises: 8c75260a6cee
Create Date: 2022-11-24 20:16:03.979476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac8a2341b50'
down_revision = '8c75260a6cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('area', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loc_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loc', ['loc_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loc_id')

    op.drop_table('loc')
    # ### end Alembic commands ###
