"""moderation

Revision ID: 5f56f2ef6cec
Revises: e3b3e4349a18
Create Date: 2022-11-28 20:25:45.719116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f56f2ef6cec'
down_revision = 'e3b3e4349a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moderation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('moderation')

    # ### end Alembic commands ###
