"""posts table

Revision ID: 73e1970c05b8
Revises: 3ada2dbd8778
Create Date: 2022-11-24 15:51:03.871649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e1970c05b8'
down_revision = '3ada2dbd8778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.String(length=140), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
