"""new fields in user model

Revision ID: 894c3bd1d53d
Revises: 610363d96151
Create Date: 2022-11-22 13:52:46.756675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894c3bd1d53d'
down_revision = '610363d96151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
