"""empty message

Revision ID: 8c75260a6cee
Revises: a93205900e65
Create Date: 2022-11-24 20:14:43.487872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c75260a6cee'
down_revision = 'a93205900e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loc',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=140), nullable=True),
    sa.Column('area', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
