"""empty message

Revision ID: 92b52944e577
Revises: 01b85a839e59
Create Date: 2022-11-24 20:42:38.426936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b52944e577'
down_revision = '01b85a839e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=140), nullable=True))
        batch_op.drop_column('Area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Area', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('area')

    op.create_table('city',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
