"""empty message

Revision ID: 992688cb0548
Revises: 14543313077d
Create Date: 2022-11-24 20:27:14.653460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992688cb0548'
down_revision = '14543313077d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loc',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=140), nullable=True),
    sa.Column('area', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
