"""new field user lowercase username

Revision ID: 9f0566403a8a
Revises: 894c3bd1d53d
Create Date: 2022-11-22 14:51:07.002240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0566403a8a'
down_revision = '894c3bd1d53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usernamelowercase', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_usernamelowercase'), ['usernamelowercase'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_usernamelowercase'))
        batch_op.drop_column('usernamelowercase')

    # ### end Alembic commands ###
