"""relationship loc activity

Revision ID: a090922efab6
Revises: cd128354c987
Create Date: 2022-11-24 20:25:41.705719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a090922efab6'
down_revision = 'cd128354c987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loc_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loc', ['loc_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loc_id')

    # ### end Alembic commands ###
