"""relationship loc activity

Revision ID: a93205900e65
Revises: 962ce055e29d
Create Date: 2022-11-24 20:00:32.515282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93205900e65'
down_revision = '962ce055e29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loc_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loc', ['loc_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loc_id')

    # ### end Alembic commands ###
