"""email lowercase

Revision ID: aba4bf135179
Revises: ad443ea45ab0
Create Date: 2022-11-23 19:07:40.281052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba4bf135179'
down_revision = 'ad443ea45ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emaillowercase', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_emaillowercase'), ['emaillowercase'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_emaillowercase'))
        batch_op.drop_column('emaillowercase')

    # ### end Alembic commands ###
