"""revert

Revision ID: b2924f9e00c2
Revises: f4f97dac523a
Create Date: 2022-11-24 16:05:25.251494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2924f9e00c2'
down_revision = 'f4f97dac523a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('location')

    op.create_table('location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(length=140), nullable=True),
    sa.Column('city', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
