"""loc table

Revision ID: cd128354c987
Revises: e1c2a7304988
Create Date: 2022-11-24 20:22:09.552123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd128354c987'
down_revision = 'e1c2a7304988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('area', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loc')
    # ### end Alembic commands ###
