"""relationships city area activities

Revision ID: eaf3d59e6582
Revises: 72e307d6fd76
Create Date: 2022-11-24 20:36:53.306646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf3d59e6582'
down_revision = '72e307d6fd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('activity_id')
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
